### ISSUE TITLE
[Feature Request] Ability to stop the deamon via CLI

### ISSUE THREAD

**Issue by rjan90** [textileio/bidbot#12]
Since I'm running bidbot daemon with nohup, having the ability to gently stop the daemon with a command like `bidbot daemon stop`, would be quite nice :smile:

**Comment by merlinran** [comment]
that suggests also actually daemonizing `bidbot` (so you don't have to `nohup`). will add to the team radar.

**Comment by merlinran** [comment]
@rjan90 For now you can send either of `SIGINT`, `SIGQUIT` or `SIGTERM` to the `bidbot` process to gracefully stop it, and the simplest to do that is `pkill bidbot`.

**Comment by rjan90** [comment]
Yeah, that’s what I have used up until now! Closing the issue for now!
