### ISSUE TITLE
Clarify permission of api-token

### ISSUE THREAD

**Issue by rjan90** [textileio/bidbot#8]
In the CLI, maybe clarify what kind of permission the ` --lotus-miner-api-token string          Lotus miner API authorization token` token needs. If it's read, write, sign or admin :smiley:

**Comment by merlinran** [comment]
good point @rjan90 ! to import data the write permission is required but not admin I suppose @jsign ?

**Comment by jsign** [comment]
Yep, `write` is needed now since the API call that `bidbot` does is:
`MarketImportDealData func(p0 context.Context, p1 cid.Cid, p2 string) error`
Which is annotated with `perm:"write"`

**Comment by merlinran** [comment]
Interestingly, what the lotus client calls is
`DealsImportData(ctx context.Context, dealPropCid cid.Cid, file string) error //perm:admin`
rather than
`MarketImportDealData(ctx context.Context, propcid cid.Cid, path string) error                                                                                                        //perm:write`

So admin is required.

**Comment by rjan90** [comment]
Yeah, was just trying to start the daemon now, and got:
`2021/07/07 14:41:23 creating lotus client: lotus client fails health check: missing permission to invoke 'DealsList' (need 'admin')`

**Comment by merlinran** [comment]
But the code of the two are exactly the same.

https://github.com/filecoin-project/lotus/blob/master/node/impl/storminer.go#L627-L635

https://github.com/filecoin-project/lotus/blob/master/node/impl/storminer.go#L416-L424

Guess we need to replace `DealsList` with another call for health check and switch to `MarketImportDealData`?

**Comment by rjan90** [comment]
Tested with the new code, got past the permission check, but it stopped at verifing the miner address:

```
2021-07-07T15:19:43.576+0200	INFO	mpeer	marketpeer/marketpeer.go:159	marketpeer 12D3KooWMZ1FtiqiHyCu28MoFw7CCKgzKmHui7mfvSUAwzhJqkz6 is online
2021/07/07 15:20:08 starting service: 1 error occurred:
	* verifying miner address: calling full node state miner info: failed to load miner actor state: unknown actor code bafkqadlgnfwc6njpmfrwg33vnz2a
```

**Comment by merlinran** [comment]
Not sure exactly what's going on, but this is probably something with `miner-addr` and `wallet-addr-sig`?

**Comment by rjan90** [comment]
Ah, that error was on me, pasted the wrong string (the wallet address) into --miner-addr, instead of the f0xx-address :smile: 

```
2021-07-07T15:37:55.045+0200	INFO	mpeer	marketpeer/marketpeer.go:159	marketpeer 12D3KooWMZ1FtiqiHyCu28MoFw7CCKgzKmHui7mfvSUAwzhJqkz6 is online
2021-07-07T15:38:20.695+0200	INFO	bidbot/service	service/service.go:213	service started
2021-07-07T15:38:21.177+0200	INFO	mpeer	marketpeer/marketpeer.go:218	peer was bootstapped
2021-07-07T15:38:21.177+0200	INFO	bidbot/service	service/service.go:274	subscribed to the deal auction feed
2021-07-07T15:38:21.177+0200	INFO	bidbot/api	httpapi/httpapi.go:43	http server started at :9999
```

**Comment by merlinran** [comment]
Nice!

**Comment by merlinran** [comment]
BTW you won't see many auctions right now, so please just keep `bidbot` running. Later on you can `bidbot deals list` to see how many auctions your `bidbot` has taken part in.

**Comment by jsign** [comment]
> But the code of the two are exactly the same.
> 
> https://github.com/filecoin-project/lotus/blob/master/node/impl/storminer.go#L627-L635
> 
> https://github.com/filecoin-project/lotus/blob/master/node/impl/storminer.go#L416-L424
> 

Yep! They're exactly the same.

> Guess we need to replace `DealsList` with another call for health check and switch to `MarketImportDealData`?
@merlinran , agree :+1:
