### ISSUE TITLE
upgrading to v0.1.10 breaks quic setup

### ISSUE THREAD

**Issue by j1v** [textileio/bidbot#96]
After upgrading to v0.1.10 starting bid bot with the old config that used to work for months dies with : 

```
2022-03-17T11:37:34.434+0200	FATAL	cli	cli@v1.0.2/cli.go:142	starting service: 1 error occurred:
	* creating peer: 1 error occurred:
	* creating peer: 1 error occurred:
	* setting up libp2p%!(EXTRA *errors.errorString=transports already registered for protocol(s): quic)
```

When a disable quic in the config : `"quic": true,` to  `"quic": false,` bidbot starts and seems to run fine.

**Comment by jsign** [comment]
@j1v , thanks for the report. I found the same problem in another system that also used QUIC and fixed it yesterday.
I'll create a PR with the fix and tag a new version for QUIC users.

Thanks!
